In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline

Using TensorFlow backend.


In [0]:
#Initialize 
seed= 7
np.random.seed(seed)

In [3]:
#load data 
import io
from google.colab import files
uploaded = files.upload()
df = pd.read_csv(io.StringIO(uploaded['iris.csv'].decode('utf-8')) , header = None)
df

Saving iris.csv to iris.csv


0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
5    5.4  3.9  1.7  0.4     Iris-setosa
6    4.6  3.4  1.4  0.3     Iris-setosa
7    5.0  3.4  1.5  0.2     Iris-setosa
8    4.4  2.9  1.4  0.2     Iris-setosa
9    4.9  3.1  1.5  0.1     Iris-setosa
10   5.4  3.7  1.5  0.2     Iris-setosa
11   4.8  3.4  1.6  0.2     Iris-setosa
12   4.8  3.0  1.4  0.1     Iris-setosa
13   4.3  3.0  1.1  0.1     Iris-setosa
14   5.8  4.0  1.2  0.2     Iris-setosa
15   5.7  4.4  1.5  0.4     Iris-setosa
16   5.4  3.9  1.3  0.4     Iris-setosa
17   5.1  3.5  1.4  0.3     Iris-setosa
18   5.7  3.8  1.7  0.3     Iris-setosa
19   5.1  3.8  1.5  0.3     Iris-setosa
20   5.4  3.4  1.7  0.2     Iris-setosa
21   5.1  3.7  1.5  0.4     Iris-setosa
22   4.6  3.6  1.0  0.2     Iris-setosa
23   5.1  3.3  1.7  0.5     Iris-setosa
24   4.8  3.4  1.9  0.2     Iris-setosa
25   5.0  3.0  1.6  0.2     Iris-setosa
26   5.0  3.4  1.6  0.4     Iris-setosa
27   5.2  3.5  1.5  0.2     Iris-setosa
28   5.2  3.4  1.4  0.2     Iris-setosa
29   4.7  3.2  1.6  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
120  6.9  3.2  5.7  2.3  Iris-virginica
121  5.6  2.8  4.9  2.0  Iris-virginica
122  7.7  2.8  6.7  2.0  Iris-virginica
123  6.3  2.7  4.9  1.8  Iris-virginica
124  6.7  3.3  5.7  2.1  Iris-virginica
125  7.2  3.2  6.0  1.8  Iris-virginica
126  6.2  2.8  4.8  1.8  Iris-virginica
127  6.1  3.0  4.9  1.8  Iris-virginica
128  6.4  2.8  5.6  2.1  Iris-virginica
129  7.2  3.0  5.8  1.6  Iris-virginica
130  7.4  2.8  6.1  1.9  Iris-virginica
131  7.9  3.8  6.4  2.0  Iris-virginica
132  6.4  2.8  5.6  2.2  Iris-virginica
133  6.3  2.8  5.1  1.5  Iris-virginica
134  6.1  2.6  5.6  1.4  Iris-virginica
135  7.7  3.0  6.1  2.3  Iris-virginica
136  6.3  3.4  5.6  2.4  Iris-virginica
137  6.4  3.1  5.5  1.8  Iris-virginica
138  6.0  3.0  4.8  1.8  Iris-virginica
139  6.9  3.1  5.4  2.1  Iris-virginica
140  6.7  3.1  5.6  2.4  Iris-virginica
141  6.9  3.1  5.1  2.3  Iris-virginica
142  5.8  2.7  5.1  1.9  Iris-virginica
143  6.8  3.2  5.9  2.3  Iris-virginica
144  6.7  3.3  5.7  2.5  Iris-virginica
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [0]:
dataset = df.values
x= dataset[:,0:4].astype(float)
y = dataset[:,4]


In [0]:
#encode class values as integers
encoder = LabelEncoder()
encoder.fit(y)
encoded_y = encoder.transform(y)

In [0]:
#Convert integers to dummy variables (i.e one hot encoding)
dummy_y = np_utils.to_categorical(encoded_y)

In [0]:
#define baseline model
def baseline_model():
  model = Sequential()
  model.add(Dense(8 , activation='relu' , input_shape=(4,)))
  model.add(Dense(3, activation = 'softmax' ))
  model.compile(optimizer = 'Adam' , loss='categorical_crossentropy' , metrics=['acc'])
  return model

In [0]:
#Run the model
estimator= KerasClassifier(build_fn = baseline_model, epochs= 200, batch_size=5 , verbose=1)

In [0]:
#kfold 
kfold= KFold(n_splits= 10, shuffle=True , random_state=seed)

In [10]:
#EVALUATE 
results= cross_val_score(estimator, x , dummy_y , cv=kfold)

W0827 06:16:48.982352 140341624829824 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0827 06:16:49.026128 140341624829824 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0827 06:16:49.034453 140341624829824 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0827 06:16:49.069063 140341624829824 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0827 06:16:49.097007 140341624829824 deprecation_wrappe

Epoch 1/200
135/135 [==============================] - 1s 6ms/step - loss: 1.2220 - acc: 0.3333 
Epoch 2/200
135/135 [==============================] - 0s 248us/step - loss: 1.1147 - acc: 0.4741
Epoch 3/200
135/135 [==============================] - 0s 218us/step - loss: 1.0348 - acc: 0.6815
Epoch 4/200
135/135 [==============================] - 0s 233us/step - loss: 0.9962 - acc: 0.6815
Epoch 5/200
135/135 [==============================] - 0s 208us/step - loss: 0.9659 - acc: 0.6815
Epoch 6/200
135/135 [==============================] - 0s 194us/step - loss: 0.9359 - acc: 0.6815
Epoch 7/200
135/135 [==============================] - 0s 197us/step - loss: 0.9076 - acc: 0.6815
Epoch 8/200
135/135 [==============================] - 0s 222us/step - loss: 0.8789 - acc: 0.6815
Epoch 9/200
135/135 [==============================] - 0s 204us/step - loss: 0.8512 - acc: 0.6815
Epoch 10/200
135/135 [==============================] - 0s 218us/step - loss: 0.8251 - acc: 0.6815
Epoch 11/200
135/135

In [11]:
print("Accuracy: %2f%%(%2f%%)"%(results.mean()*100,results.std()*100))

Accuracy: 97.333333%(4.422166%)


In [0]:
#to build smaller network

def smaller_model():
  smaller_model=Sequential()
  smaller_model.add(Dense(4, activation='relu' , input_shape=(4,)))
  smaller_model.add(Dense(3, activation='softmax'))
  smaller_model.compile(optimizer='Adam' , loss='categorical_crossentropy' , metrics=['accuracy'])
  return smaller_model

In [13]:
#Run 
estimator= KerasClassifier(build_fn= smaller_model , epochs= 100 , batch_size= 5 , verbose=0)
kfold = KFold(n_splits=10 , shuffle= True , random_state= seed)
results= cross_val_score(estimator , x , dummy_y , cv= kfold)
print('smaller_model: %2f%%(%2f%%)' %(results.mean()*100 , results.std()*100))


smaller_model: 92.000000%(13.266499%)


In [0]:
#Larger_model
def larger_model():
  larger_model= Sequential()
  larger_model.add(Dense(16 , activation='relu' , input_shape=(4,)))
  larger_model.add(Dense(8 , activation='relu'))
  larger_model.add(Dense(3 , activation='softmax'))
  larger_model.compile(optimizer = 'rmsprop' , loss= 'categorical_crossentropy' , metrics=['accuracy'])
  return larger_model

In [15]:
#RUN
estimator=KerasClassifier(build_fn= larger_model , epochs=100 , batch_size=5 , verbose=0)
kfold=KFold(n_splits=10 , shuffle=True , random_state=seed)
results= cross_val_score(estimator , x , dummy_y , cv=kfold)
print('larger_model :  %2f%%(%2f%%)' %(results.mean()*100 , results.std()*100))

larger_model :  98.666667%(2.666667%)


In [17]:
#Model that ovefits
def overfit_model():
  overfit_model= Sequential()
  overfit_model.add(Dense(12 , activation='relu' , input_shape=(4,)))
  overfit_model.add(Dense(10 , activation='relu'))
  overfit_model.add(Dense(8 , activation='relu'))
  overfit_model.add(Dense(3 , activation='softmax'))
  overfit_model.compile(optimizer='rmsprop' , loss='categorical_crossentropy' ,metrics=['acc'])
  return overfit_model

estimator = KerasClassifier(build_fn = overfit_model , epochs= 200 , batch_size= 5 , verbose=0)
kfold= KFold(n_splits=10 , shuffle=True , random_state= seed)
results= cross_val_score(estimator , x , dummy_y , cv=kfold)
print('Overfit_Model : %2f%%(%2f%%)' %(results.mean()*100 , results.std()*100))

Overfit_Model : 96.000000%(4.422166%)


In [0]:
# Using functional API 
from keras.layers import Input , Dense
from keras.models import Model
def fun_model():
  a = Input(shape=(4,))
  z= Dense(8 , activation='relu')(a)
  b = Dense(3, activation='softmax')(z)
  model = Model(a,b)
  model.compile(optimizer='Adam' , loss= 'categorical_crossentropy' , metrics=['acc'])
  return model

In [19]:
estimator = KerasClassifier(build_fn = fun_model , epochs = 200 , batch_size = 5 , verbose=0)
kfold = KFold(n_splits = 10 , shuffle= True , random_state= seed)
results= cross_val_score(estimator , x , dummy_y , cv= kfold)
print('Accuracy: %2f%%(%2f%%)' %(results.mean()*100 , results.std()*100))

Accuracy: 96.666667%(3.333333%)


In [0]:
#Model Subclassing
import tensorflow as tf
class SubclassModel (tf.keras.Model):
  def __init__(self):
    super(SubclassModel , self).__init__()
    self.dense1 = tf.keras.layers.Dense(8 , activation=tf.nn.relu)
    self.dense2 = tf.keras.layers.Dense(6 , activation= tf.nn.relu)
    self.dense3 = tf.keras.layers.Dense(3 , activation= tf.nn.softmax)
    
  def call(self, a):
    x= self.dense1(a)
    x= self.dense2(x)
    return self.dense3(x)
def lastModel():
  model= SubclassModel()
  model.compile(optimizer='Adam' , loss= 'categorical_crossentropy' , metrics=['acc'])
  return model
 

In [23]:
estimator= KerasClassifier(build_fn= lastModel , epochs= 200 , batch_size= 5 , verbose=0)
kfold= KFold(n_splits=10 , shuffle=True , random_state= seed)
results = cross_val_score(estimator , x , dummy_y , cv=kfold)
print('Accuracy: %2f%%(%2f%%)' %(results.mean()*100 , results.std()*100))

W0827 06:50:22.162568 140341624829824 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


Accuracy: 88.666667%(21.092389%)


In [27]:
#build model from scratch
complete_data= dataset.copy()
np.random.shuffle(complete_data)
data = complete_data[:,0:4].astype('float32')
labels= complete_data[:,4]
le= LabelEncoder()
le.fit(labels)
encode_labels= le.transform(labels).astype('float32')
one_hot_encode_labels= np_utils.to_categorical(encode_labels)
print(one_hot_encode_labels)
print(data.dtype)
train_dataset = data[:100]
test_dataset = data[100:]
train_label= one_hot_encode_labels[:100]
test_label = one_hot_encode_labels[100:]
print(train_label.shape)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0.

In [0]:
def build_model():
  model= Sequential()
  model.add(Dense(4 , activation='relu' , input_shape=(4,)))
  model.add(Dense(3 , activation='softmax'))
  model.compile(optimizer='Adam' , loss='categorical_crossentropy' , metrics=['acc'])
  return model

In [32]:
#kfold
k=4
num_val_samples= len(train_dataset)//k
num_epochs= 200

for i in range(k):
  print('processing fold #' , i)
  val_data= train_dataset[i*num_val_samples: (i+1)*num_val_samples]
  val_labels= train_label[i* num_val_samples : (i+1) * num_val_samples]
  partial_train_data = np.concatenate([train_dataset[:i *num_val_samples], train_dataset[(i+1)*num_val_samples:]], axis=0)
  partial_train_labels= np.concatenate([train_label[:i*num_val_samples], train_label[(i+1)*num_val_samples:]])
  model = build_model()
  model.fit(partial_train_data , partial_train_labels, validation_data=(val_data, val_labels), epochs=num_epochs, batch_size=1 , verbose=0)
  loss, acc= model.evaluate(val_data , val_labels , verbose=0)
  print(acc)

processing fold # 0
0.9200000166893005
processing fold # 1
1.0
processing fold # 2
1.0
processing fold # 3
1.0


In [34]:
def last_Model():
  model=Sequential()
  model.add(Dense(4 , activation='relu' , input_shape= (4,)))
  model.add(Dense(3, activation='softmax'))
  model.compile(optimizer='Adam' , loss= 'categorical_crossentropy' , metrics=['acc'])
  return model

model= last_Model()
model.fit(train_dataset , train_label, epochs= 100 , batch_size=5 , verbose=0)

In [35]:
history = model.evaluate(test_dataset , test_label)
history

50/50 [==============================] - 2s 36ms/step


[0.5511597847938537, 0.6799999976158142]